# Docker Compose for AutoDockr development
version: '3.8'

services:
  autodockr-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: autodockr-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge